### ISSUE TITLE
Legal

### ISSUE THREAD

**Issue by FinnT730** [ahmed605/Modern-MCP#9]
Is this even legal to use the MCP-Config in this way? Since it's licence says something else.
Read this thread on Discord: [here](https://discordapp.com/channels/313125603924639766/570666026077913098/593632955922907137)

He does not like that you do it this way.

**Comment by ahmed605** [comment]
This is based on FG not MCPconfig and this is legal but it's not legal to share any code generated by this tool.

**Comment by Earthcomputer** [comment]
It's not legal to host MCPConfig on your own maven repo, which you appear to be doing.

**Comment by ahmed605** [comment]
> It's not legal to host MCPConfig on your own maven repo, which you appear to be doing.

Wait, I don't have maven repo

**Comment by LexManos** [comment]
The illegal part is the redistribution of MCPConfig and related data. Which you DO NOT have the rights to do so.
The entire premise of this 'project' is however scummy as hell. All it is is a <100 line build.gradle file that uses ForgeGradle. All of the actual heavy lifting and functionality is coming from FG.
You then slap your logo and names all over it as if it was a unique creative work.
You also slap some tracking callbacks onto it so that you can see everyone who uses it {Yes Artifactory tracks users if you want it to} and considering they have no functional use, I have to assume it's for data tracking. 

You also have a fundamental lack of understanding on how FG actually works. As shown by the 'download assets' issue, your runclient task, and just your general attitude when handling issues/users.

My suggestion to everyone who visits this repo: Stop using this. It's a horrible way to learn, it's done incorrectly, And if you just want to see the Minecraft Source in MCP names. Then use FG directly. Do not give credit/attention to shitty projects like these.

**Comment by ahmed605** [comment]
> The illegal part is the redistribution of MCPConfig and related data. Which you DO NOT have the rights to do so.
> The entire premise of this 'project' is however scummy as hell. All it is is a <100 line build.gradle file that uses ForgeGradle. All of the actual heavy lifting and functionality is coming from FG.
> You then slap your logo and names all over it as if it was a unique creative work.
> You also slap some tracking callbacks onto it so that you can see everyone who uses it {Yes Artifactory tracks users if you want it to} and considering they have no functional use, I have to assume it's for data tracking.
> 
> You also have a fundamental lack of understanding on how FG actually works. As shown by the 'download assets' issue, your runclient task, and just your general attitude when handling issues/users.
> 
> My suggestion to everyone who visits this repo: Stop using this. It's a horrible way to learn, it's done incorrectly, And if you just want to see the Minecraft Source in MCP names. Then use FG directly. Do not give credit/attention to shitty projects like these.

@LexManos 

- I will remove all maven repos except MinecraftForge rebo 

- the target of this project is to get the MCP mapped source quickly without rewriting new build.gradle 

- I write in the readme that that tool is based on FG

- Also I don't know what is tracking callbacks

- and if you want me to edit some files in this rebo tell me what is the files you want to edit

- and about 'download assets' issue I was going to tell him the fix but I saw your comment

**Comment by LexManos** [comment]
> the target of this project is to get the MCP mapped source quickly without rewriting new build.gradle

[Here](https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/build.gradle#L53-L59) Your entire project is obsolete now. They can just use that section of Forge's build.gradle instead of yours. As you can clearly see that's the section you copy/pasted, poorly, to make this 'project'.

Seriously dude, all you need is a 10 line gist and this project is useless.

You are clearly showing you have no idea what you are doing. Nore what tools or data is used in this process.

As it sits i'm going to have to tell you to stop using the MCP name/branding in its entirety. As you most definitely do not have permission to use it in your advertisements.

Again, to anyone who wants to see Minecraft decompiled code in MCP names. Use the official tools, and don't support people like this who take other's work and label it as their own.

**Comment by ahmed605** [comment]
@LexManos Ok :

- I will change the rebo name

- I know this rebo is useless for some people but some people don't know how to use FG al all.

- the rebos (tools or data) you talk about is from old repo (https://github.com/Hexeption/PRE-MCP) that fork this repo from (and I will remove it)

- about copied code from MinecraftForge build.gradle it's not secret I said to @Justsnoopy30 this thing before

**Comment by Earthcomputer** [comment]
> I know this rebo is useless for some people but some people don't know how to use FG al all.
Why not create documentation for these people in this case, rather than this crap? Heck, the required code would even be small enough to fit in a 1 page doc.

And btw, it's "repo" not "rebo".

**Comment by FinnT730** [comment]
If you believe this will work, prove to me that THIS is useful. Because what I can see from this, you try to remake MCP the way you want. Did you even ask Hexepition that you can use his work??
